### ISSUE TITLE
Can't get cube source record size.

### ISSUE THREAD

**Issue by Yancey0623** [KylinOLAP/Kylin#101]
Dear All!
I deploy kylin on Apache Hadoop, when i build the job ,  it failed on the last step. here is the some log message:

``` java
[QuartzScheduler_Worker-4]:[2014-11-24 19:24:47,280][INFO][com.kylinolap.job.flow.JobFlowListener.jobWasExecuted(JobFlowListener.java:93)] - cube_job_group.test_kylin_cube_without_slr_empty.30bbd69c-33ae-4983-aaf7-f46ab42b88dd.14 status: FINISHED
[QuartzScheduler_Worker-4]:[2014-11-24 19:24:47,280][DEBUG][com.kylinolap.cube.CubeManager.loadCubeInstance(CubeManager.java:604)] - Loading CubeInstance kylin_metadata_qa(key='/cube/test_kylin_cube_without_slr_empty.json')@kylin_metadata_qa@hbase:192.168.44.21:2181:/hbase9827
[QuartzScheduler_Worker-4]:[2014-11-24 19:24:47,295][DEBUG][com.kylinolap.common.persistence.ResourceStore.putResource(ResourceStore.java:166)] - Saving resource /job/30bbd69c-33ae-4983-aaf7-f46ab42b88dd (Store kylin_metadata_qa@hbase:192.168.44.21:2181:/hbase9827)
[QuartzScheduler_Worker-4]:[2014-11-24 19:24:47,300][INFO][com.kylinolap.job.flow.JobFlowListener.updateCubeSegmentInfoOnSucceed(JobFlowListener.java:238)] - Updating cube segment FULL_BUILD for cube test_kylin_cube_without_slr_empty
[QuartzScheduler_Worker-4]:[2014-11-24 19:24:47,301][ERROR][com.kylinolap.job.flow.JobFlowListener.jobWasExecuted(JobFlowListener.java:117)] - Can't get cube source record size.
java.lang.RuntimeException: Can't get cube source record size.
        at com.kylinolap.job.flow.JobFlowListener.updateCubeSegmentInfoOnSucceed(JobFlowListener.java:274)
        at com.kylinolap.job.flow.JobFlowListener.jobWasExecuted(JobFlowListener.java:99)
        at org.quartz.core.QuartzScheduler.notifyJobListenersWasExecuted(QuartzScheduler.java:1985)
        at org.quartz.core.JobRunShell.notifyJobListenersComplete(JobRunShell.java:340)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

here is some version info:
Kylin 0.6.2
hadoop 2.4.1
hbase 0.98.4-hadoop2
zookeeper 3.4.5
hive 0.13.0

I find some config info on hbase

```
get 'kylin_metadata_qa_job', '/job/1eaf05f8-e9f5-4dd7-9748-ab9b3098a512'
{
    "uuid": "1eaf05f8-e9f5-4dd7-9748-ab9b3098a512",
    "name": "test_kylin_cube_without_slr_empty - FULL_BUILD - BUILD - PST 2014-11-24 23:00:15",
    "type": "BUILD",
    "duration": 461,
    "steps": [
        {
            "name": "Create Intermediate Flat Hive Table",
            "info": null,
            "interruptCmd": null,
            "sequence_id": 0,
            "exec_cmd": "hive -e "DROPTABLEIFEXISTSkylin_intermediate_test_kylin_cube_without_slr_desc_FULL_BUILD_1eaf05f8_e9f5_4dd7_9748_ab9b3098a512;nCREATEEXTERNALTABLEIFNOTEXISTSkylin_intermediate_test_kylin_cube_without_slr_desc_FULL_BUILD_1eaf05f8_e9f5_4dd7_9748_ab9b3098a512n(nCAL_DTdaten,
            LEAF_CATEG_IDintn,
            LSTG_SITE_IDintn,
            META_CATEG_NAMEstringn,
            CATEG_LVL2_NAMEstringn,
            CATEG_LVL3_NAMEstringn,
            LSTG_FORMAT_NAMEstringn,
            SLR_SEGMENT_CDsmallintn,
            PRICEdecimal(38,
            16)n,
            SELLER_IDbigintn)
...}
]
```

in source code: com.kylinolap.job.flow.JobFlowListener.updateCubeSegmentInfoOnSucceed(JobFlowListener.java:272)

```
               JobStep createFlatTableStep = jobInstance.findStep(JobConstants.STEP_NAME_CREATE_FLAT_HIVE_TABLE);
                if (null != createFlatTableStep) {
                    String sourceRecordsSize = createFlatTableStep.getInfo(JobInstance.SOURCE_RECORDS_SIZE);
                    if (sourceRecordsSize == null || sourceRecordsSize.equals("")) {
                        throw new RuntimeException("Can't get cube source record size.");
                    }
                    sourceSize = Long.parseLong(sourceRecordsSize);
                } else {
                    log.info("No step with name '" + JobConstants.STEP_NAME_CREATE_FLAT_HIVE_TABLE + "' is found");
                }
```

the "info" is null, cased throw a RuntimeException,  some one have idea with it??

**Comment by dabaus** [comment]
I had this problem, and it turned out it was because i had configured hive to use tez, not mr.

**Comment by vonsuu** [comment]
Hi, 

I'am trying to build my first cube using Apache Kylin, everything goes fine until last step where I'm getting error:

    java.lang.IllegalStateException: Can't get cube source record count.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at org.apache.kylin.job.cube.UpdateCubeInfoAfterBuildStep.doWork(UpdateCubeInfoAfterBuildStep.java:104)
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:107)
	at org.apache.kylin.job.execution.DefaultChainedExecutable.doWork(DefaultChainedExecutable.java:50)
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:107)
	at org.apache.kylin.job.impl.threadpool.DefaultScheduler$JobRunner.run(DefaultScheduler.java:132)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

According to this issue above error occurs because Kylin attempt to find this pattern in hive's output: "HDFS Read: (\d+) HDFS Write: (\d+) SUCCESS".

Correct output from cube building tutorial: github.com/KylinOLAP/Kylin/wiki/Kylin-Cube-Build-and-Job-Monitoring-Tutorial:

http://i.imgur.com/71tEeIy.png

My output in Kylin looks corrupted:

http://i.imgur.com/GCbrN03.png

However when I check Hive log it looks ok:

    2015-05-27 08:40:13,419 INFO  [main]: ql.Driver (Driver.java:execute(1285)) - Starting command: 
    INSERT OVERWRITE TABLE kylin_intermediate_Kubek_19700101000000_2922789940817071255_f23ac1b1_10fe_4112_ac9e_b4e6baf07654 SELECT
    FACT_TABLE.DATE
    ,FACT_TABLE.MONEY_ADVERTISER
    ,FACT_TABLE.MONEY_PUBLISHER
    FROM DEFAULT.ADVSTATS as FACT_TABLE 
    ...
    2015-05-27 08:45:05,132 INFO  [main]: ql.Driver (SessionState.java:printInfo(824)) - MapReduce Jobs Launched: 
    2015-05-27 08:45:05,148 INFO  [main]: ql.Driver (SessionState.java:printInfo(824)) - Stage-Stage-1: Map: 1   Cumulative CPU: 17.32 sec   HDFS Read: 44644035 HDFS Write: 2347008 SUCCESS
    2015-05-27 08:45:05,153 INFO  [main]: ql.Driver (SessionState.java:printInfo(824)) - Total MapReduce CPU Time Spent: 17 seconds 320 msec
    2015-05-27 08:45:05,167 INFO  [main]: ql.Driver (SessionState.java:printInfo(824)) - OK

I'm using Hortonworks Sandbox 2.2:

    hadoop-2.6.0
    hbase-0.98.12
    hive-0.14.0
    zookeeper-3.4.6

Can someone tell me why my kylin logs preview looks like that and first of all is that could be a reason of last step error?

**Comment by binmahone** [comment]
The fastest way to get response from our developers is to send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org

**Comment by shaofengshi** [comment]
That is possible, as hadoop may fail to get counter sometimes even if the job succeed; We observed this problem in our deployment, and to bypass it I made a commit on 0.6 branch in last week (see https://github.com/apache/incubator-kylin/commit/a4692dba681bc2f136e02c64565639eb0080fcc9); 

Please discard your current job, and submit it again, then see whether this time it can finish all steps; If not, it may relate with the specific hadoop output format in your env;

If need, I can make the same change on v0.7 branch;

**Comment by shaofengshi** [comment]
We have moved to Apache git and use Apache JIRA to track the issues; This repository has been abandoned; Please subscribe our mailing list for any public discussion (as hongbin mentioned above); see you there;
