### ISSUE TITLE
Install scripted finished in my virtual machine, but cannot visit via http://localhost:9080

### ISSUE THREAD

**Issue by binmahone** [KylinOLAP/Kylin#12]

**Comment by flowerteaw** [comment]
I used option2,but the netword failed to start.
after login, I use command 'service network restart', the error is:
Determining IP information for eth0... faile. 

Did I make anything wrong?

**Comment by binmahone** [comment]
hi @flowerteaw

Bridge mode is a common usage for VMs to get independent ips
i suggest you consult your IT admins, it should be some network issues.

**Comment by flowerteaw** [comment]
Thank you for answering. When I use other VMs, they work well.
I tried Hortonwork sandbox 2.1 both vmware and virtualbox in bridged mode,  the networks both failed.I didn't download Kylin in these two trials.

**Comment by binmahone** [comment]
NAT will also do the job:)

**Comment by janzhongi** [comment]
Hi  @flowerteaw
Are you using wireless?

" On Linux hosts, functionality is limited when using wireless interfaces for bridged networking. Currently, VirtualBox supports only IPv4 over wireless. For other protocols such as IPv6 and IPX, you must choose a wired interface."

**Comment by flowerteaw** [comment]
@binmahone 
NAT works well， but I need to visit Kylin from another pc.

@janzhongi 
I'm using wired mode and my host is Win7.

**Comment by binmahone** [comment]
hi @flowerteaw 

how about NAT + Port Forwarding solution?

**Comment by flowerteaw** [comment]
@binmahone 
Port Forwarding solution works well, thanks a lot!

**Comment by hackersOfhackers** [comment]
Hi,
I am able to open sandbox hortonworks on address 127.0.0.1:8080. when i downloaded kylin on sandox and run script bin/kylin.sh start. it gives output as follows.

KYLIN_HOME is set to incubator-kylin/
cat: incubator-kylin//conf/kylin.properties: No such file or directory
15/04/01 18:48:40 WARN conf.HiveConf: HiveConf of name hive.optimize.mapjoin.mapreduce does not exist
15/04/01 18:48:40 WARN conf.HiveConf: HiveConf of name hive.heapsize does not exist
15/04/01 18:48:40 WARN conf.HiveConf: HiveConf of name hive.server2.enable.impersonation does not exist
15/04/01 18:48:40 WARN conf.HiveConf: HiveConf of name hive.auto.convert.sortmerge.join.noconditionaltask does not exist

Logging initialized using configuration in file:/etc/hive/conf/hive-log4j.properties
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/hdp/2.2.0.0-2041/hadoop/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/2.2.0.0-2041/hive/lib/hive-jdbc-0.14.0.2.2.0.0-2041-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
hive dependency: /etc/hive/conf:/usr/hdp/2.2.0.0-2041/hive/lib/*:/usr/hdp/2.2.0.0-2041/falcon/webapp/falcon/WEB-INF/lib/hive-hcatalog-core-0.14.0.2.2.0.0-2041.jar
KYLIN_JVM_SETTINGS is not set, using default jvm settings
KYLIN_DEBUG_SETTINGS is not set, will not enable remote debuging
KYLIN_LD_LIBRARY_SETTINGS is not set, lzo compression at MR and hbase might not work
A new Kylin instance is started by root, stop it using "kylin.sh stop"
Please visit http://<ip>:7070/kylin
You can check the log at bin/../tomcat/logs/kylin.log
[root@sandbox incubator-kylin]# bin/kylin.sh: line 50: incubator-kylin//pid: No such file or directory
bin/kylin.sh: line 39: bin/../tomcat/logs/kylin.log: No such file or directory

now i am trying to open 127.0.0.1:7070/kylin. it is not working. I tried bridge mode as well as NAT (port forwarding).please help me in this.

Thanks
