### ISSUE TITLE
Support same column name in different lookup table

### ISSUE THREAD

**Issue by lukehan** [KylinOLAP/Kylin#307]
When there are two lookup table using same name in one cube, the cube engine will raise exception since it do not know which column coming from which table.

Using full qualified name with _database.tablename.columnname_ to unique identify column in row key.

Workaround: duplicate lookup table with specified name and join with fact.
For example: duplicate dw_countries to dw_countries_seller and dw_countries_buyer.

**Comment by qhzhou** [comment]
Here is a workground,
a constraint has been added, that user cannot sync tables with same name but different db.
The issue will be fixed when a metadata refactor is done.

**Comment by lukehan** [comment]
Please continue update to JIRA: https://issues.apache.org/jira/browse/KYLIN-198
