### ISSUE TITLE
Urgent--Kylin:Job Failure--You do not own the lock: /kylin/job_engine/lock/Build_Test_Cube_Engine

### ISSUE THREAD

**Issue by abhsnh** [KylinOLAP/Kylin#335]
The new fact table has been written to $KYLIN_METADATA_URL/data/TEST_KYLIN_FACT.csv

SCP file /tmp/TEST_CAL_DT.csv to /tmp/kylin
L4J [2015-01-01 03:49:53,423][INFO][org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation] - Closing master protocol: MasterService
L4J [2015-01-01 03:49:53,422][DEBUG][com.kylinolap.job.engine.JobEngine] - Closing HBASE connection
Exception in thread "Thread-11" java.lang.RuntimeException: java.lang.IllegalMonitorStateException: You do not own the lock: /kylin/job_engine/lock/Build_Test_Cube_Engine
	at com.kylinolap.job.engine.JobEngine.releaseLock(JobEngine.java:107)
	at com.kylinolap.job.engine.JobEngine.access$100(JobEngine.java:49)
	at com.kylinolap.job.engine.JobEngine$1.run(JobEngine.java:90)
Caused by: java.lang.IllegalMonitorStateException: You do not own the lock: /kylin/job_engine/lock/Build_Test_Cube_Engine
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:128)
	at com.kylinolap.job.engine.JobEngine.releaseLock(JobEngine.java:98)
	... 2 more
L4J [2015-01-01 03:49:53,456][INFO][org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation] - Closing zookeeper sessionid=0x14aa44c0b92002e
L4J [2015-01-01 03:49:53,460][INFO][org.apache.zookeeper.ClientCnxn] - EventThread shut down
L4J [2015-01-01 03:49:53,460][INFO][org.apache.zookeeper.ZooKeeper] - Session: 0x14aa44c0b92002e closed

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Kylin:HadoopOLAPEngine ............................. SUCCESS [  0.004 s]
[INFO] Kylin:AtopCalcite .................................. SUCCESS [  2.521 s]
[INFO] Kylin:Common ....................................... SUCCESS [  1.436 s]
[INFO] Kylin:Metadata ..................................... SUCCESS [  0.224 s]
[INFO] Kylin:Dictionary ................................... SUCCESS [  0.238 s]
[INFO] Kylin:Cube ......................................... SUCCESS [  1.019 s]
[INFO] Kylin:Job .......................................... FAILURE [ 49.139 s]
[INFO] Kylin:Storage ...................................... SKIPPED
[INFO] Kylin:Query ........................................ SKIPPED
[INFO] Kylin:RESTServer ................................... SKIPPED
[INFO] Kylin:Jdbc ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by abhsnh** [comment]
Need help on this...!

**Comment by binmahone** [comment]
sorry we're on holiday for the last three days.
the exception here is not enough for diagnosing the problem, can you check out the catalina log in tomcat to see if there's any detailed exceptions?
also, can you elaborate on your environment?

**Comment by abhsnh** [comment]
Hey, this is actually an Off Hadoop CLI installation. The Hadoop services are running on EC2 instances and I am trying to deploy Kylin on a different machine that would access these Hadoop services 
I followed the tutorial for Off Hadoop installing maven first. Then running the test: mvn clean install -DskipTests
Modified the hosts file.
and then while running the test: mvn test -Dtest=com.kylinolap.job.BuildCubeWithEngineTest -DfailIfNoTests=false, I got an interrupt. There is no tomcat required probably in this installation.

**Comment by binmahone** [comment]
i got it. is there any exception logs before the snippet you provided?

**Comment by abhsnh** [comment]
No.

**Comment by abhsnh** [comment]
Another exception in the middle: Connection refused...
L4J [2015-01-04 00:52:09,948][DEBUG][com.kylinolap.metadata.MetadataManager] - Loading InvertedIndexDesc kylin_metadata_qa(key='/invertedindex_desc/test_kylin_cube_ii.json')@kylin_metadata_qa@hbase:sandbox.hortonworks.com:2181:/hbase-unsecure
L4J [2015-01-04 00:52:09,955][DEBUG][com.kylinolap.metadata.MetadataManager] - Loaded 1 Inverted Index Desc(s)
L4J [2015-01-04 00:52:09,961][DEBUG][com.kylinolap.common.restclient.Broadcaster] - Broadcast nodeUri: sandbox.hortonworks.com:7070, type: cube, action: update, name: TEST_KYLIN_CUBE_WITHOUT_SLR_READY
L4J [2015-01-04 00:52:09,979][INFO][com.kylinolap.cube.project.ProjectManager] - Initializing CubeManager with metadata url kylin_metadata_qa@hbase:sandbox.hortonworks.com:2181:/hbase-unsecure
L4J [2015-01-04 00:52:10,015][DEBUG][com.kylinolap.cube.project.ProjectManager] - Loading Project from folder kylin_metadata_qa(key='/project')@kylin_metadata_qa@hbase:sandbox.hortonworks.com:2181:/hbase-unsecure
L4J [2015-01-04 00:52:10,031][INFO][org.apache.commons.httpclient.HttpMethodDirector] - I/O exception (java.net.ConnectException) caught when processing request: Connection refused
L4J [2015-01-04 00:52:10,031][INFO][org.apache.commons.httpclient.HttpMethodDirector] - Retrying request
L4J [2015-01-04 00:52:10,033][INFO][org.apache.commons.httpclient.HttpMethodDirector] - I/O exception (java.net.ConnectException) caught when processing request: Connection refused
L4J [2015-01-04 00:52:10,033][INFO][org.apache.commons.httpclient.HttpMethodDirector] - Retrying request
L4J [2015-01-04 00:52:10,035][INFO][org.apache.commons.httpclient.HttpMethodDirector] - I/O exception (java.net.ConnectException) caught when processing request: Connection refused
L4J [2015-01-04 00:52:10,035][INFO][org.apache.commons.httpclient.HttpMethodDirector] - Retrying request
L4J [2015-01-04 00:52:10,037][WARN][com.kylinolap.common.restclient.Broadcaster] - Thread failed during wipe cache at cube.update.TEST_KYLIN_CUBE_WITHOUT_SLR_READY, java.net.ConnectException: Connection refused
L4J [2015-01-04 00:52:10,082][DEBUG][com.kylinolap.cube.project.ProjectManager] - Loaded 3 Project(s)
L4J [2015-01-04 00:52:10,082][INFO][com.kylinolap.cube.CubeManager] - Cube with 1 segments is saved
L4J [2015-01-04 00:52:10,085][INFO][com.kylinolap.cube.CubeManager] - Updating cube instance 'test_kylin_cube_without_slr_empty
L4J [2015-01-04 00:52:10,086][DEBUG][com.kylinolap.common.persistence.ResourceStore] - Saving resource /cube/test_kylin_cube_without_slr_empty.json (Store kylin_metadata_qa@hbase:sandbox.hortonworks.com:2181:/hbase-unsecure)
L4J [2015-01-04 00:52:10,090][DEBUG][com.kylinolap.metadata.MetadataManager] - Reloading SourceTable from folder kylin_metadata_qa(key='/table')@kylin_metadata_qa@hbase:sandbox.hortonworks.com:2181:/hbase-unsecure
L4J [2015-01-04 00:52:10,128][DEBUG][com.kylinolap.metadata.MetadataManager] - Loading SourceTable kylin_metadata_qa(key='/table/TEST_CAL_DT.json')@kylin_metadata_qa@hbase:sandbox.hortonworks.com:2181:/hbase-unsecure
L4J [2015-01-04 00:52:10,142][DEBUG][com.kylinolap.metadata.MetadataManager] - Loading SourceTable kylin_metadata_qa(key='/table/TEST_CATEGORY_GROUPINGS.json')@kylin_metadata_qa@hbase:sandbox.hortonworks.com:2181:/hbase-unsecure

**Comment by abhsnh** [comment]
However the process does not terminate on connection refused... It just gives a warning and continues until it stops at the initial snippet.

**Comment by abhsnh** [comment]
Hey, got any solution for it?

**Comment by abhsnh** [comment]
Guys, any inputs? Need this to be sorted out soon.

**Comment by lukehan** [comment]
Is there any firewall between your kylin machine and EC2 instances?

**Comment by abhsnh** [comment]
No
