### ISSUE TITLE
How to recover existing cubes when migrating to new version of Kylin?

### ISSUE THREAD

**Issue by pktippa** [KylinOLAP/Kylin#338]
Hi Team,

I have migrated the Kylin version from 0.6.2 to 0.6.3 by pulling the source from tagged version.
But I lost all my previously built cubes in 0.6.2 after migrating to 0.6.3.

Please let me know how to recover the cubes when we run the ./deploy.sh again?

Thanks,
P K Tippa.

**Comment by binmahone** [comment]
hi, @pktippa ,

i'm afraid we don't have a tool for that. i wrote a wiki for your case:
https://github.com/KylinOLAP/Kylin/wiki/Kylin-Metadata-Store

**Comment by lukehan** [comment]
We should offer metadata migrate tool in future release.
