### ISSUE TITLE
enum switch case label must be the unqualified name of an enumeration constant   

### ISSUE THREAD

**Issue by suyan0613** [KylinOLAP/Kylin#373]
what's matter with  /home/bigdata/Kylin-master/job/src/main/java/com/kylinolap/job/tools/HadoopStatusChecker.java:[98,22] an enum switch case label must be the unqualified name of an enumeration constant   
when i do ./deploy.sh

**Comment by lukehan** [comment]
could you please let's know more detail about your question?

Thanks.
