### ISSUE TITLE
Can't rebuild Kylin after started HBase on Hortonworks Sandbox

### ISSUE THREAD

**Issue by RCFans** [KylinOLAP/Kylin#425]
It is similar to issue #9 

I started HBase then rebuild Kylin, but it was still trying to connect to Horonworks HBase rather than my local sandbox, does it mean Kylin hard codes HBase url to somewhere?

I have to remove all (apache tomcat, maven repository and npm).

**Comment by binmahone** [comment]
hi, 

please put your question to mail list: dev@kylin.incubator.apache.org
and can you be more specific on you question? like how you installed Kylin, you env, and error message?

thanks
hongbin
