### ISSUE TITLE
hcatalog lib not found

### ISSUE THREAD

**Issue by zhouming2015** [KylinOLAP/Kylin#462]
i install in my linux(centos6) use apache hive0.13, apache hbase0.98, apache hadoop2.4.0,
kylin0.7.1， 
when I run  kylin.sh start,  i have an issue about    hcatalog lib not found,

i didn't the reason.
please help me

**Comment by binmahone** [comment]
The fastest way to get response from our developers is to send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org

**Comment by zhouming2015** [comment]
I have write letter to dev@kylin.incubator.apache.org 2 days ago and  receive no letter from now on.

**Comment by binmahone** [comment]
hi,

can you give me some keyword of your previous email? i don't recall seeing your email in our dev list.

**Comment by zhouming2015** [comment]
hi, here is my question:


I   try   to    install  kylin,  here is my install enviroment:
 
apache hive0.13.1
 apache  hbase0.98
 apache  zookeeper3.4.6
 apache  hadoop2.5.2
 kylin0.7.1,


when i try to  execute  kylin.sh start    , there are some issues:  
KYLIN_HOME is set to /home/apacheHadoop/kylin
Logging initialized using configuration in file:/home/apacheHadoop/hive-0.13.1/conf/hive-log4j.properties
hcatalog lib  not found


best wishes 
 thx.










At 2015-05-14 20:01:36, "hongbin ma" <notifications@github.com> wrote:


hi,

can you give me some keyword of your previous email? i don't recall seeing your email in our dev list.

**Comment by binmahone** [comment]
hi, i failed to find you mail in mail list... it's wield
anyway, kylin requires hive 0.14 or later, please try a newer version of hdp(like 2.2) or cdh

**Comment by shaofengshi** [comment]
Kylin will seek hive-hcatalog-core*.jar; please check whether you have installed that; With HDP and CDH, these are already configured well; BTW, Mailing list didn't receive your email; Please try again; We can discuss there.

Date: Thu, 14 May 2015 06:56:10 -0700

**Comment by zhouming2015** [comment]
hi, i want know  the mailing list is   dev@kylin.incubator.apache.org   or  Kylin@noreply.github.com   ?
and how to write lettle to you mailing list? 

I had write lettle to dev@kylin.incubator.apache.org   in  2015-5-15 16:45  by my email ligongda2006@126.com ,  is that  the correct way  to  kylin mailing list ??

**Comment by binmahone** [comment]
send any message to dev-subscribe@kylin.incubator.apache.org, then your'll subscribe our mail list.(there might be another confirming letter)

if you want post any question to our mail list, send message to dev@kylin.incubator.apache.org

**Comment by binmahone** [comment]
can you still find the email in your "sent mails"? can you send another mail as a test?

**Comment by zhouming2015** [comment]
yes， i have  send a message to dev-subscribe@kylin.incubator.apache.org as a  test,
and i will write my question to  dev@kylin.incubator.apache.org. 
thx

**Comment by zhouming2015** [comment]
hi  i bulid the sample cube with project learn_kylin , and the result is error,
the log detail is ：

java.lang.IncompatibleClassChangeError:Found interface org.apache.hadoop.mapreduce.JobContext,
but class was expected:
at org.apache.hive.hcatalog.mapreduce.HcatBaseInputFormat.getSplits(HCatBaseInputFormat.java 102)

I use apahce hive0.14,   and i want know if my hive version is not right or something else i dont konw.

thx

**Comment by binmahone** [comment]
we still don't your email in mail list..
please try with another email and make it work in mail list, because we're supposed to discuss all of issues on mail list instead of github.

as shaofeng said, we find hive-hcatalog-core*.jar in your hive's libs. make make sure its verson >= 0.14
you can check it by lsof command.
if things still don't work, you may start from a standard sandbox like HDP 2.2

**Comment by liamlee** [comment]
Hi,
I got the same issue:
"java.lang.IncompatibleClassChangeError:Found interface org.apache.hadoop.mapreduce.JobContext,
but class was expected"

My environment：
apache hive 1.0.1
 apache  hbase 1.0.1.1
 apache  zookeeper3.4.6
 apache  hadoop2.6.0
 kylin0.7.2

Can anyone help this?

**Comment by binmahone** [comment]
The fastest way to get response from our developers is to send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org

please discuss in mail thread

**Comment by lukehan** [comment]
Github Issues here will be closed soon, please open JIRA instead of discuss here:
http://issues.apache.org/jira/browse/KYLIN

or, send mail to Kylin dev mailing list as Hongbin mentioned above.

Thanks.

**Comment by zjost** [comment]
I fixed this by modifying the "/bin/find-hive-dependency.sh" file.  The problem was the line that set the "hdp_home" variable.  The awk -F command was looking for a string like "/hive.*/lib/" but the most recent install of Hive has directory format "/apache-hive.*/lib/".  I merely changed the line to read '/apache-hive.*/lib/'.  

Your results may be different if your install directory is different.  Add a line "echo $hive_exec_path" before the hdp_home line to see what's stored in the variable.

**Comment by lukehan** [comment]
Hi @zjost 
Could you please help to open one JIRA and attache patch for this?
We will review and merge into coming release.

Thank you very much

**Comment by zjost** [comment]
Luke,

Not sure I'm the best person to offer a robust solution.  I merely changed
the directory path regex expression to work for my install environment.

**Comment by lukehan** [comment]
@zjost, if it works for you, it should be reference for others at least, more beyond that it could be update by community;-)

Don't hesitate to raise any change to us, we are welcome and will help to review to make sure it works very well.

I have forwarded to mailing list, you could found here:

and please jump into there for further discussion and comments.
http://apache-kylin-incubating.74782.x6.nabble.com/FW-Kylin-hcatalog-lib-not-found-462-tt1003.html

Thanks.

**Comment by kongliangzhong** [comment]
thanks @zjost , i fix this problem. env: ubuntu12.04. hive1.2.1

**Comment by kongliangzhong** [comment]
I got the same problem when am trying to deploy kylin on ubuntu12.04.  and fix it using @zjost 's approach. thanks.
