### ISSUE TITLE
Error using JDBC or ODBC in Cognos

### ISSUE THREAD

**Issue by blake-liu** [KylinOLAP/Kylin#465]
cognos:10.2.1 express + win7 x64
kylin 0.7 + centos6.5
---------------------------------------------------------------------------------------------------------
1. error using odbc
    a) odbc configuration
    ![1](https://cloud.githubusercontent.com/assets/12573124/7834054/5a351bee-049e-11e5-912d-77f590fdd907.png)
    b)datasource configuration in cognos
    ![2 2](https://cloud.githubusercontent.com/assets/12573124/7840928/1dcd6bc4-04cc-11e5-9c93-77117f40a3df.png)

    c)odbc connection test
    ![3 2](https://cloud.githubusercontent.com/assets/12573124/7840940/2aeeff52-04cc-11e5-8f5d-d5b522256c55.png)
--------------------------------------------------------------------------------------------------------
2. error using jdbc
    a)datasource configuration in cognos
    ![4 2](https://cloud.githubusercontent.com/assets/12573124/7840943/32402b96-04cc-11e5-9ead-cd8b070b34ef.png)

    b)jdbc connection test
    ![5 2](https://cloud.githubusercontent.com/assets/12573124/7840947/39189048-04cc-11e5-852a-409f0aa480c1.png)

**Comment by lukehan** [comment]
This Github Issues is closed already.

Please open JIRA for any Kylin relative issue: [http://issues.apache.org/jira/browse/KYLIN](http://issues.apache.org/jira/browse/KYLIN) 

or send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org
