### ISSUE TITLE
execute ./kylin.sh start   error on ubuntu linux 0.14 

### ISSUE THREAD

**Issue by xiangtao** [KylinOLAP/Kylin#468]
when i run ./kylin.sh start on ubuntu linux 0.14 for kylin-0.7.1-incubating version  ,but i got an error ./kylin.sh: 23: ./find-hive-dependency.sh: Syntax error: "(" unexpected .

is anything uncompatible ?

**Comment by lukehan** [comment]
This Github Issues is closed already.

Please open JIRA for any Kylin relative issue: http://issues.apache.org/jira/browse/KYLIN

or send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org
