### ISSUE TITLE
A problem during RUN sample queries.

### ISSUE THREAD

**Issue by cs-wang** [KylinOLAP/Kylin#473]
I build the sample cube 100%

but when I run query select part_dt, sum(price) as total_selled, count(distinct seller_id) as sellers from kylin_sales group by part_dt order by part_dt;

the web gives:
Error while executing SQL "select part_dt, sum(price) as total_selled, count(distinct seller_id) as sellers from kylin_sales group by part_dt order by part_dt LIMIT 50000": Error in coprocessor

kylin.log is here: [http://pan.baidu.com/s/1sk9hREt](http://pan.baidu.com/s/1sk9hREt)

Any advice to it?

**Comment by liyang-gmt8** [comment]
Hi there. Please post questions / issues to user@kylin.apache.org

Thanks.

**Comment by cs-wang** [comment]
请问：发出去的邮件能否有回复？
